In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier , RandomForestClassifier
from sklearn.preprocessing import StandardScaler ,  LabelEncoder
from sklearn.metrics import accuracy_score ,  precision_score , recall_score

In [29]:
data = pd.read_csv("C:\\Users\\cngan\\Downloads\\Titanic-Dataset.csv")

In [30]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [32]:
data.drop(columns=['PassengerId','Name','Ticket',], inplace=True)

In [33]:
data.shape

(891, 9)

In [34]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [36]:
data.Cabin.fillna(value=data.Cabin.mode()[0].split()[1], inplace=True)

C:\Users\cngan\AppData\Local\Temp\ipykernel_2416\2205744946.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Cabin.fillna(value=data.Cabin.mode()[0].split()[1], inplace=True)

In [37]:
data.Age.fillna(data.Age.mean() , inplace=True)

C:\Users\cngan\AppData\Local\Temp\ipykernel_2416\1122637831.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Age.fillna(data.Age.mean() , inplace=True)

In [38]:
data.dropna(inplace=True)

In [39]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    0
dtype: int64

In [40]:
data.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   B98        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   B98        S

In [41]:
encoder = LabelEncoder()
data.Sex = encoder.fit_transform(data.Sex)
data.Cabin = encoder.fit_transform(data.Cabin)
data.Embarked = encoder.fit_transform(data.Embarked)

In [42]:
data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1  22.0      1      0   7.2500     47         2
1         1       1    0  38.0      1      0  71.2833     81         0
2         1       3    0  26.0      0      0   7.9250     47         2
3         1       1    0  35.0      1      0  53.1000     55         2
4         0       3    1  35.0      0      0   8.0500     47         2

In [43]:
std_scaler = StandardScaler()
data.Age = std_scaler.fit_transform(data[["Age"]])
data.Fare =  std_scaler.fit_transform(data[["Fare"]])

In [44]:
data.head()

   Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Cabin  Embarked
0         0       3    1 -0.590495      1      0 -0.500240     47         2
1         1       1    0  0.643971      1      0  0.788947     81         0
2         1       3    0 -0.281878      0      0 -0.486650     47         2
3         1       1    0  0.412509      1      0  0.422861     55         2
4         0       3    1  0.412509      0      0 -0.484133     47         2

In [45]:
x= data.drop(columns="Survived")
y = data.Survived

In [46]:
x_train ,x_test ,y_train, y_test = train_test_split(x,y , random_state=42 , test_size=0.2)

In [47]:
base_model = DecisionTreeClassifier(max_depth=1 , random_state=42 )

In [48]:
base_model

DecisionTreeClassifier(max_depth=1, random_state=42)

In [49]:
classifier = AdaBoostClassifier(random_state=42 , estimator=base_model , n_estimators= 100)
classifier

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1,
                                                    random_state=42),
                   n_estimators=100, random_state=42)

In [50]:
classifier.fit(x_train , y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1,
                                                    random_state=42),
                   n_estimators=100, random_state=42)

In [51]:
pred = classifier.predict(x_test)

In [52]:
pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [53]:
accuracy_score(pred,y_test)

0.8033707865168539

In [54]:
recall_score(pred,y_test)

0.7236842105263158