In [255]:
import numpy as np
import pandas as pd

In [256]:
data=pd.Series([1,2,3,4,5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [257]:
data=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [258]:
type(data)

pandas.core.series.Series

In [259]:
data.name="Numbers"

In [260]:
data.size

5

In [261]:
data

a    1
b    2
c    3
d    4
e    5
Name: Numbers, dtype: int64

In [262]:
data.shape

(5,)

In [263]:
data.values

array([1, 2, 3, 4, 5])

In [264]:
data[-2]

C:\Users\cngan\AppData\Local\Temp\ipykernel_8768\2140106112.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[-2]

np.int64(4)

In [265]:
data["a"],data["b"]

(np.int64(1), np.int64(2))

In [266]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [267]:
data.loc["a"],data.iloc[3]

(np.int64(1), np.int64(4))

In [268]:
data.loc["a"::2],data.iloc[3]

(a    1
 c    3
 e    5
 Name: Numbers, dtype: int64,
 np.int64(4))

In [269]:
data.loc[["a","c","e"]],data.iloc[3]

(a    1
 c    3
 e    5
 Name: Numbers, dtype: int64,
 np.int64(4))

In [270]:
##data frames

In [271]:
dictionaries={
    "usn":[1,2,3,4,5],
    "name":["gana","bhoomika","kavya","hitha","neha"],
    "age":[21,20,23,24,22],
    "branch":["cs","ece","eee","csbs","aids"]
}

In [272]:
df=pd.DataFrame(dictionaries)
df

   usn      name  age branch
0    1      gana   21     cs
1    2  bhoomika   20    ece
2    3     kavya   23    eee
3    4     hitha   24   csbs
4    5      neha   22   aids

In [273]:
data=pd.read_csv("C:\\Users\\cngan\\Downloads\\sample.csv")

In [274]:
data

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,2015-09-30,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,2021-11-05,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,2010-04-18,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2022-02-14,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,2013-12-01,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,2020-08-19,Bangalore,4.0
10,10,111,Ravi,HR,33,47000,6,2017-05-23,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,2019-09-17,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,2008-03-11,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,2021-07-29,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,2014-01-10,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [275]:
data.head()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,2015-09-30,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1

In [276]:
data.tail()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [277]:
data.describe()

,Unnamed: 0,EmpID,Age,Salary,Experience,PerformanceScore
count,20.00000,20.00000,20.000000,20.000000,20.000000,20.000000
mean,9.50000,110.50000,32.700000,59875.000000,7.400000,4.190000
std,5.91608,5.91608,5.449288,13388.796377,4.615762,0.415363
min,0.00000,101.00000,25.000000,45000.000000,2.000000,3.500000
25%,4.75000,105.75000,28.750000,50750.000000,4.000000,3.900000
50%,9.50000,110.50000,31.500000,56500.000000,6.000000,4.150000
75%,14.25000,115.25000,36.250000,61250.000000,10.250000,4.425000
max,19.00000,120.00000,45.000000,90000.000000,18.000000,4.900000

In [278]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20 non-null     int64
 1   EmpID             20 non-null     int64
 2   Name              20 non-null     object
 3   Department        20 non-null     object
 4   Age               20 non-null     int64
 5   Salary            20 non-null     int64
 6   Experience        20 non-null     int64
 7   JoiningDate       20 non-null     object
 8   City              20 non-null     object
 9   PerformanceScore  20 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 1.7+ KB

In [279]:
data.shape

(20, 10)

In [280]:
data.sample()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1

In [281]:
data.Department

0          IT
1          HR
2     Finance
3          IT
4          HR
5     Finance
6          IT
7          HR
8     Finance
9          IT
10         HR
11    Finance
12         IT
13         HR
14    Finance
15         IT
16         HR
17    Finance
18         IT
19         HR
Name: Department, dtype: object

In [282]:
data["Name"]

0       Ram
1     Shyam
2     Geeta
3     Anita
4     Kiran
5      John
6     Meena
7     David
8      Sara
9     Arjun
10     Ravi
11    Priya
12    Kunal
13    Sneha
14    Vijay
15     Neha
16     Amit
17    Pooja
18    Rahul
19    Divya
Name: Name, dtype: object

In [283]:
data[["Age","Salary","City"]]

    Age  Salary       City
0    25   50000  Bangalore
1    30   45000     Mumbai
2    28   60000      Delhi
3    35   75000  Bangalore
4    32   52000     Mumbai
5    29   58000      Delhi
6    41   82000  Bangalore
7    26   48000     Mumbai
8    38   61000      Delhi
9    27   54000  Bangalore
10   33   47000     Mumbai
11   31   59000      Delhi
12   45   90000  Bangalore
13   29   51000     Mumbai
14   36   62000      Delhi
15   40   88000  Bangalore
16   34   53000     Mumbai
17   30   57000      Delhi
18   28   56000  Bangalore
19   37   49500     Mumbai

In [284]:
type(data.Name)

pandas.core.series.Series

In [285]:
data=pd.read_csv("C:\\Users\\cngan\\Downloads\\test2.csv")

In [286]:
data

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [287]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6 non-null      int64
 1   Name        6 non-null      object
 2   Age         5 non-null      float64
 3   Department  6 non-null      object
 4   Salary      5 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 372.0+ bytes

In [288]:
data.describe()

       Unnamed: 0        Age        Salary
count    6.000000   5.000000      5.000000
mean     2.500000  28.800000  58400.000000
std      1.870829   4.147288   8532.291603
min      0.000000  25.000000  50000.000000
25%      1.250000  25.000000  50000.000000
50%      2.500000  29.000000  60000.000000
75%      3.750000  30.000000  62000.000000
max      5.000000  35.000000  70000.000000

In [289]:
data.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [290]:
data.isnull()

   Unnamed: 0   Name    Age  Department  Salary
0       False  False  False       False   False
1       False  False  False       False   False
2       False  False  False       False   False
3       False  False   True       False   False
4       False  False  False       False    True
5       False  False  False       False   False

In [291]:
data.loc["0":"4","Name":"Department"]

      Name   Age Department
0    Alice  25.0         HR
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT
4      Eve  29.0         HR

In [292]:
data.iloc[1:4,1:4]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [293]:
data.columns

Index(['Unnamed: 0', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [294]:
data.rename(columns={"Name":"People","Age":"A"},inplace=True)

In [295]:
data

   Unnamed: 0   People     A Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [296]:
data

   Unnamed: 0   People     A Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [297]:
data.drop('Department',axis=1)

   Unnamed: 0   People     A   Salary
0           0    Alice  25.0  50000.0
1           1      Bob  30.0  60000.0
2           2  Charlie  35.0  70000.0
3           3    David   NaN  62000.0
4           4      Eve  29.0      NaN
5           5    Alice  25.0  50000.0

In [298]:
data["update_salary"]=data["Salary"]+500

In [299]:
data

   Unnamed: 0   People     A Department   Salary  update_salary
0           0    Alice  25.0         HR  50000.0        50500.0
1           1      Bob  30.0         IT  60000.0        60500.0
2           2  Charlie  35.0    Finance  70000.0        70500.0
3           3    David   NaN         IT  62000.0        62500.0
4           4      Eve  29.0         HR      NaN            NaN
5           5    Alice  25.0         HR  50000.0        50500.0

In [300]:
data["update_salary"]=data["Salary"].map(lambda x:x+1000)

In [301]:
data

   Unnamed: 0   People     A Department   Salary  update_salary
0           0    Alice  25.0         HR  50000.0        51000.0
1           1      Bob  30.0         IT  60000.0        61000.0
2           2  Charlie  35.0    Finance  70000.0        71000.0
3           3    David   NaN         IT  62000.0        63000.0
4           4      Eve  29.0         HR      NaN            NaN
5           5    Alice  25.0         HR  50000.0        51000.0

In [302]:
data["usn"]=[41,42,43,44,45,46]

In [303]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David   NaN         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [304]:
data.isnull().sum()

Unnamed: 0       0
People           0
A                1
Department       0
Salary           1
update_salary    1
usn              0
dtype: int64

In [305]:
data[data["A"]>25]

   Unnamed: 0   People     A Department   Salary  update_salary  usn
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
4           4      Eve  29.0         HR      NaN            NaN   45

In [306]:
data.head()

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David   NaN         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45

In [307]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David   NaN         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [308]:
data["Department"].value_counts()

Department
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [309]:
data["A"] = data["A"].fillna(method="ffill")

C:\Users\cngan\AppData\Local\Temp\ipykernel_8768\2392186993.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["A"] = data["A"].fillna(method="ffill")

In [310]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David  35.0         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [311]:
data["A"] = data["A"].fillna(data["A"].mean())

In [312]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David  35.0         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [313]:
data["A"] = data["A"].fillna(method="ffill")

C:\Users\cngan\AppData\Local\Temp\ipykernel_8768\2392186993.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["A"] = data["A"].fillna(method="ffill")

In [314]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David  35.0         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR      NaN            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [315]:
data["Salary"] = data["Salary"].fillna(method="bfill")

C:\Users\cngan\AppData\Local\Temp\ipykernel_8768\1976282591.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Salary"] = data["Salary"].fillna(method="bfill")

In [316]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David  35.0         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR  50000.0            NaN   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [317]:
data.A.ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: A, dtype: float64

In [319]:
data["update_salary"] = data["update_salary"].fillna(data["update_salary"].mean())

In [320]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        51000.0   41
1           1      Bob  30.0         IT  60000.0        61000.0   42
2           2  Charlie  35.0    Finance  70000.0        71000.0   43
3           3    David  35.0         IT  62000.0        63000.0   44
4           4      Eve  29.0         HR  50000.0        59400.0   45
5           5    Alice  25.0         HR  50000.0        51000.0   46

In [322]:
data["update_salary"]=data["Salary"].apply(lambda x:x+500)

In [323]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn
0           0    Alice  25.0         HR  50000.0        50500.0   41
1           1      Bob  30.0         IT  60000.0        60500.0   42
2           2  Charlie  35.0    Finance  70000.0        70500.0   43
3           3    David  35.0         IT  62000.0        62500.0   44
4           4      Eve  29.0         HR  50000.0        50500.0   45
5           5    Alice  25.0         HR  50000.0        50500.0   46

In [328]:
##row wise apply
data["level"]=data.apply(lambda s:"High" if s["update_salary"] > 60000 else "low" ,axis=1)

In [329]:
data

   Unnamed: 0   People     A Department   Salary  update_salary  usn level
0           0    Alice  25.0         HR  50000.0        50500.0   41   low
1           1      Bob  30.0         IT  60000.0        60500.0   42  High
2           2  Charlie  35.0    Finance  70000.0        70500.0   43  High
3           3    David  35.0         IT  62000.0        62500.0   44  High
4           4      Eve  29.0         HR  50000.0        50500.0   45   low
5           5    Alice  25.0         HR  50000.0        50500.0   46   low

In [331]:
data.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         50000.0
IT         61000.0
Name: Salary, dtype: float64

In [338]:
filtered=data[(data["A"] > 28) & (data["Department"] == "IT")]

In [339]:
filtered

   Unnamed: 0 People     A Department   Salary  update_salary  usn level
1           1    Bob  30.0         IT  60000.0        60500.0   42  High
3           3  David  35.0         IT  62000.0        62500.0   44  High

In [333]:
products=pd.Series([700,150,300],index=["Laptop","Mouse","Keyboard"]
                  )
print("Full Serises")
print(products)

Full Serises
Laptop      700
Mouse       150
Keyboard    300
dtype: int64

In [340]:
print("\nPrice of Laptop:")
print(products.loc["Laptop"])

Price of Laptop:
700

In [343]:
print("\nFirst two products (positional slicing):")
print(products.iloc[:2])

First two products (positional slicing):
Laptop    700
Mouse     150
dtype: int64

In [344]:
import pandas as pd
grades = pd.Series([85, None, 92, 45, None, 78, 55])
print("Original Series:")
print(grades)

Original Series:
0    85.0
1     NaN
2    92.0
3    45.0
4     NaN
5    78.0
6    55.0
dtype: float64

In [346]:
print("\nMissing Values (True means missing):")
print(grades.isnull())

Missing Values (True means missing):
0    False
1     True
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [352]:
filled_grades = grades.fillna(0)

print("\nSeries After Filling Missing Values:")
print(filled_grades)

Series After Filling Missing Values:
0    85.0
1     0.0
2    92.0
3    45.0
4     0.0
5    78.0
6    55.0
dtype: float64

In [357]:
filtered_grades = filled_grades[filled_grades > 60]

print("\nScores Greater Than 60:")
print(filtered_grades)

Scores Greater Than 60:
0    85.0
2    92.0
5    78.0
dtype: float64

In [358]:
import pandas as pd

usernames = pd.Series([' Alice ', 'bOB', ' Charlie_Data ', 'daisy'])

print("Original Usernames:")
print(usernames)

Original Usernames:
0            Alice
1               bOB
2     Charlie_Data
3             daisy
dtype: object

In [359]:
cleaned_usernames = usernames.str.strip().str.lower()

print("\nCleaned Usernames:")
print(cleaned_usernames)

Cleaned Usernames:
0           alice
1             bob
2    charlie_data
3           daisy
dtype: object

In [360]:
contains_a = cleaned_usernames.str.contains('a')

print("\nNames Containing Letter 'a':")
print(contains_a)

Names Containing Letter 'a':
0     True
1    False
2     True
3     True
dtype: bool